#This is python code to display ('hello world")
print("Hello World")
print("foss practical on github")
#This is python code to display ("hello world")
print("Hello World")
print(foss practical on github")
print (fycs batch A)
print (AMC COLLEGE)
